cernanalysispreservation/cap-client

- CONTRIBUTING.rst
- cap_client/__init__.py
- cap_client/version.py
- pytest.ini
- run-tests.sh
- setup.cfg
- tests/pytest.py
- tests/test_version.py
> tests: adds test suite

- .coveragerc
- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- setup.py
- tests/test_cap_api.py
- tests/test_cli.py
> cli: adds CLI skeleton and ping method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
> cli: use access_token for oauth

- MANIFEST.in
- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/version.py
- run-tests.sh
> cli: adds get method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
> cli: adds create method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
> cli: adds delete method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
> cli: adds update method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
* Retrieves all available analyses types.
> cli: adds types method

- cap_client/cap_api.py
- cap_client/cli/cli.py
> cli: returns pretty json response

- cap_client/errors.py
> cli: add StatusCodeException in separate file

- cap_client/cap_api.py
Co-authored-by: Anna Trzcinska <anna.trzcinska@cern.ch>
> api: adds validator to update method

- cap_client/cap_api.py
- cap_client/cli/cli.py
- cap_client/errors.py
- tests/conftest.py
- tests/test_cap_api.py
- tests/test_cli.py
Co-authored-by: Anna Trzcinska <anna.trzcinska@cern.ch>
> tests: adds test for ping method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
> cli: add option for insecure connection with server

- cap_client/cap_api.py
- cap_client/cli/cli.py
- tests/conftest.py
- tests/test_cap_api.py
- tests/test_cli.py
> tests: add tests for CapAPI class

- .coveragerc
- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- tests/test_cap_api.py
> cli: add patch method

- cap_client/cap_api.py
- tests/test_cap_api.py
> tests: add tests

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- tests/test_cap_api.py
> global: removes insecure parameter

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- tests/conftest.py
- tests/test_cap_api.py
Closes: #40
Signed-off-by: Ana Trisovic ana.trisovic@cern.ch
> cli: added get_metadata method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
* Fetches user info
* References #44.
> cli: adds me command

- .coveragerc
- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/cli/metadata_cli.py
- tests/test_cap_api.py
> cli: add set and append methods

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/cli/metadata_cli.py
- cap_client/utils.py
closes: #48 
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>
> cli: clean output

- cap_client/cap_api.py
- cap_client/cli/cli.py
> cli: adds possibility to pass directly json from cli

- cap_client/cap_api.py
- cap_client/cli/cli.py
> cli: adds option to retrieve analysis from user

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/permissions_cli.py
- tests/conftest.py
- tests/test_cap_api.py
> api: adds option to get only permissions of deposit

- cap_client/cap_api.py
> cli: remove duplicated method

- cap_client/cap_api.py
- cap_client/cli/files_cli.py
- cap_client/cli/metadata_cli.py
- tests/test_cap_api.py
> cli: add files download command

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/cli/files_cli.py
- cap_client/cli/metadata_cli.py
- tests/test_cap_api.py
> cli: get-shared command

- cap_client/cap_api.py
> cli: use basic serializer in get all command

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/errors.py
- tests/test_cap_api.py
> api: get schema of analysis

- docs/index.rst
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>
> docs: change details in instructions

- cap_client/cap_api.py
- docs/index.rst
- tests/test_cap_api.py
> client: final cosmetics before first release

- README.md
- docs/index.rst
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>
> docs: add cap-cli description

- docs/index.rst
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>
> docs: fix a typo

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- tests/test_cap_api.py
> api: remove validator from create and update

- CHANGES.rst
- cap_client/version.py
> release: v1.0.0

- .travis.yml
- cap_client/cap_api.py
- pytest.ini
- setup.py
- tests/test_cap_api.py
> global: python3 compatibility

- cap_client/version.py
> release: v1.1.0

- cap_client/cap_api.py
- cap_client/cli/repositories_cli.py
- tests/test_cap_api.py
> cli: get repositories method

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- tests/conftest.py
> cli: fix double slashes in urls issue

- cap_client/cap_api.py
- cap_client/cli/files_cli.py
> cli: change command from files list to files get

- cap_client/cli/repositories_cli.py
> cli: change message on repository upload

- cap_client/errors.py
> cli: improve the `BadStatusCode` error message

- cap_client/cap_api.py
- cap_client/cli/permissions_cli.py
- tests/test_cap_api.py
> cli: format data sent in permission methods

- cap_client/cap_api.py
- cap_client/cli/cli.py
- cap_client/utils.py
- tests/test_cap_api.py
> cli: update get-schema method

- cap_client/cap_api.py
- tests/test_cap_api.py
> cli: add error handling for `download` method

- .gitignore
- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/cli/files_cli.py
- cap_client/cli/metadata_cli.py
- cap_client/cli/permissions_cli.py
- cap_client/cli/repositories_cli.py
- cap_client/errors.py
- cap_client/utils.py
- setup.py
- tests/test_cap_api.py
> cli: refactor exceptions logging

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- tests/test_cap_api.py
> cli: bring back update method

- cap_client/cap_api.py
- cap_client/cli/metadata_cli.py
- tests/test_cap_api.py
> cli: fix `metadata get` command for array elements

- cap_client/cap_api.py
- cap_client/cli/cli.py
- cap_client/errors.py
- cap_client/utils.py
- tests/test_cap_api.py
> cli: update create method

- cap_client/cap_api.py
- cap_client/cli/metadata_cli.py
- cap_client/errors.py
- cap_client/utils.py
- tests/test_cap_api.py
- tests/test_metadata_api.py
> cli: remove `metadata append` cmd

- cap_client/cli/cli.py
- cap_client/cli/files_cli.py
- cap_client/cli/metadata_cli.py
- cap_client/cli/permissions_cli.py
- cap_client/cli/repositories_cli.py
- cap_client/utils.py
> cli: add decorator for pid_option reuse

- cap_client/cap_api.py
- cap_client/cli/cli.py
- cap_client/cli/metadata_cli.py
- cap_client/utils.py
- tests/test_cap_api.py
- tests/test_deposit_api.py
> cli: add `MutuallyExclusiveOption` and use for json params

- cap_client/cap_api.py
- cap_client/cli/__init__.py
- cap_client/cli/cli.py
- cap_client/errors.py
- tests/test_cap_api.py
> cli: bring back patch method

- cap_client/api/analysis_api.py
- cap_client/cli/analysis_cli.py
- cap_client/utils.py
> cli: show new PID on publishing

- cap_client/cli/metadata_cli.py
- cap_client/cli/repositories_cli.py
- tests/conftest.py
- tests/test_analysis_cli.py
- tests/test_files_cli.py
- tests/test_metadata_cli.py
- tests/test_permissions_cli.py
- tests/test_repositories_cli.py
> tests: use CliRunner to test the whole workflow

- cap_client/cli/__init__.py
- tests/test_version.py
> global: add `version` command

- tests/test_permissions_cli.py
* update tests according to the new cap serializer
> permissions: update tests

- docs/book.json
* adds 'theme-cap'
* updates links and display configs
Signed-off-by: Pamfilos Fokianos <pamfilosf@gmail.com>
> docs: updates gitbook config and layout

- docs/book.json
Signed-off-by: Pamfilos Fokianos <pamfilosf@gmail.com>
> docs: update header nav links

- docs/README.md
- docs/book.json
Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>
> docs: fix urls and minor readme update

- cap_client/api/analysis_api.py
- cap_client/cli/analysis_cli.py
- cap_client/cli/metadata_cli.py
- cap_client/cli/permissions_cli.py
- cap_client/utils.py
utils: add custom classes for arguments handling (by @Lilykos)
> cli: add type, query, search option in analysis cli

- cap_client/api/analysis_api.py
- cap_client/cli/analysis_cli.py
- tests/e2e/cassettes/test_analysis_get_drafts_with_page_with_results.yaml
- tests/e2e/cassettes/test_analysis_get_drafts_with_page_without_results.yaml
- tests/e2e/cassettes/test_analysis_get_drafts_with_size.yaml
- tests/e2e/cassettes/test_analysis_get_drafts_with_sort.yaml
- tests/e2e/test_analysis_cli.py
- tests/unit/test_analysis_cli.py
1. Docker Compose
2. Local Env
closes #164
> analysis: add sort, size and page option for draft and records

- cap_client/cli/files_cli.py
- tests/e2e/cassettes/test_files_upload_and_download.yaml
- tests/e2e/test_files_cli.py
> files: ask user when overwriting local file on files download

- cap_client/cli/analysis_cli.py
- cap_client/cli/metadata_cli.py
- cap_client/cli/permissions_cli.py
- cap_client/utils.py
- tests/unit/test_analysis_cli.py
- tests/unit/test_metadata_cli.py
- tests/unit/test_permissions_cli.py
> metadata: allow to pass text or number as value to update

- tests/e2e/test_analysis_cli.py
- Fixes the e2e testing error of cap-client
> tests: add sleep in between creation of records in e2e tests
